# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: coprocess_object.proto for package 'coprocess'

require 'grpc'
require 'coprocess_object_pb'

module Coprocess
  module Dispatcher
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'coprocess.Dispatcher'

      rpc :Dispatch, Object, Object
      rpc :DispatchEvent, Event, EventReply
    end

    Stub = Service.rpc_stub_class
  end
end
