// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coprocess_common.proto

#include "coprocess_common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace coprocess {
class StringSliceDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StringSlice>
      _instance;
} _StringSlice_default_instance_;
}  // namespace coprocess
namespace protobuf_coprocess_5fcommon_2eproto {
static void InitDefaultsStringSlice() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::coprocess::_StringSlice_default_instance_;
    new (ptr) ::coprocess::StringSlice();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::coprocess::StringSlice::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_StringSlice =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsStringSlice}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_StringSlice.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::coprocess::StringSlice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::coprocess::StringSlice, items_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::coprocess::StringSlice)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::coprocess::_StringSlice_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "coprocess_common.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026coprocess_common.proto\022\tcoprocess\"\034\n\013S"
      "tringSlice\022\r\n\005items\030\001 \003(\t*O\n\010HookType\022\013\n"
      "\007Unknown\020\000\022\007\n\003Pre\020\001\022\010\n\004Post\020\002\022\017\n\013PostKey"
      "Auth\020\003\022\022\n\016CustomKeyCheck\020\004b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 154);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "coprocess_common.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_coprocess_5fcommon_2eproto
namespace coprocess {
const ::google::protobuf::EnumDescriptor* HookType_descriptor() {
  protobuf_coprocess_5fcommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_coprocess_5fcommon_2eproto::file_level_enum_descriptors[0];
}
bool HookType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void StringSlice::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StringSlice::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StringSlice::StringSlice()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_coprocess_5fcommon_2eproto::scc_info_StringSlice.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:coprocess.StringSlice)
}
StringSlice::StringSlice(const StringSlice& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      items_(from.items_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:coprocess.StringSlice)
}

void StringSlice::SharedCtor() {
}

StringSlice::~StringSlice() {
  // @@protoc_insertion_point(destructor:coprocess.StringSlice)
  SharedDtor();
}

void StringSlice::SharedDtor() {
}

void StringSlice::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StringSlice::descriptor() {
  ::protobuf_coprocess_5fcommon_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_coprocess_5fcommon_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StringSlice& StringSlice::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_coprocess_5fcommon_2eproto::scc_info_StringSlice.base);
  return *internal_default_instance();
}


void StringSlice::Clear() {
// @@protoc_insertion_point(message_clear_start:coprocess.StringSlice)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  _internal_metadata_.Clear();
}

bool StringSlice::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:coprocess.StringSlice)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_items()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->items(this->items_size() - 1).data(),
            static_cast<int>(this->items(this->items_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "coprocess.StringSlice.items"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:coprocess.StringSlice)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:coprocess.StringSlice)
  return false;
#undef DO_
}

void StringSlice::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:coprocess.StringSlice)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string items = 1;
  for (int i = 0, n = this->items_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->items(i).data(), static_cast<int>(this->items(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "coprocess.StringSlice.items");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->items(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:coprocess.StringSlice)
}

::google::protobuf::uint8* StringSlice::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:coprocess.StringSlice)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string items = 1;
  for (int i = 0, n = this->items_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->items(i).data(), static_cast<int>(this->items(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "coprocess.StringSlice.items");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->items(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:coprocess.StringSlice)
  return target;
}

size_t StringSlice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coprocess.StringSlice)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string items = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->items_size());
  for (int i = 0, n = this->items_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->items(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StringSlice::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:coprocess.StringSlice)
  GOOGLE_DCHECK_NE(&from, this);
  const StringSlice* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StringSlice>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:coprocess.StringSlice)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:coprocess.StringSlice)
    MergeFrom(*source);
  }
}

void StringSlice::MergeFrom(const StringSlice& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:coprocess.StringSlice)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
}

void StringSlice::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:coprocess.StringSlice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StringSlice::CopyFrom(const StringSlice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coprocess.StringSlice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StringSlice::IsInitialized() const {
  return true;
}

void StringSlice::Swap(StringSlice* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StringSlice::InternalSwap(StringSlice* other) {
  using std::swap;
  items_.InternalSwap(CastToBase(&other->items_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StringSlice::GetMetadata() const {
  protobuf_coprocess_5fcommon_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_coprocess_5fcommon_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace coprocess
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::coprocess::StringSlice* Arena::CreateMaybeMessage< ::coprocess::StringSlice >(Arena* arena) {
  return Arena::CreateInternal< ::coprocess::StringSlice >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
