// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coprocess_mini_request_object.proto

#ifndef PROTOBUF_INCLUDED_coprocess_5fmini_5frequest_5fobject_2eproto
#define PROTOBUF_INCLUDED_coprocess_5fmini_5frequest_5fobject_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "coprocess_return_overrides.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_coprocess_5fmini_5frequest_5fobject_2eproto 

namespace protobuf_coprocess_5fmini_5frequest_5fobject_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_coprocess_5fmini_5frequest_5fobject_2eproto
namespace coprocess {
class MiniRequestObject;
class MiniRequestObjectDefaultTypeInternal;
extern MiniRequestObjectDefaultTypeInternal _MiniRequestObject_default_instance_;
class MiniRequestObject_AddParamsEntry_DoNotUse;
class MiniRequestObject_AddParamsEntry_DoNotUseDefaultTypeInternal;
extern MiniRequestObject_AddParamsEntry_DoNotUseDefaultTypeInternal _MiniRequestObject_AddParamsEntry_DoNotUse_default_instance_;
class MiniRequestObject_ExtendedParamsEntry_DoNotUse;
class MiniRequestObject_ExtendedParamsEntry_DoNotUseDefaultTypeInternal;
extern MiniRequestObject_ExtendedParamsEntry_DoNotUseDefaultTypeInternal _MiniRequestObject_ExtendedParamsEntry_DoNotUse_default_instance_;
class MiniRequestObject_HeadersEntry_DoNotUse;
class MiniRequestObject_HeadersEntry_DoNotUseDefaultTypeInternal;
extern MiniRequestObject_HeadersEntry_DoNotUseDefaultTypeInternal _MiniRequestObject_HeadersEntry_DoNotUse_default_instance_;
class MiniRequestObject_ParamsEntry_DoNotUse;
class MiniRequestObject_ParamsEntry_DoNotUseDefaultTypeInternal;
extern MiniRequestObject_ParamsEntry_DoNotUseDefaultTypeInternal _MiniRequestObject_ParamsEntry_DoNotUse_default_instance_;
class MiniRequestObject_SetHeadersEntry_DoNotUse;
class MiniRequestObject_SetHeadersEntry_DoNotUseDefaultTypeInternal;
extern MiniRequestObject_SetHeadersEntry_DoNotUseDefaultTypeInternal _MiniRequestObject_SetHeadersEntry_DoNotUse_default_instance_;
}  // namespace coprocess
namespace google {
namespace protobuf {
template<> ::coprocess::MiniRequestObject* Arena::CreateMaybeMessage<::coprocess::MiniRequestObject>(Arena*);
template<> ::coprocess::MiniRequestObject_AddParamsEntry_DoNotUse* Arena::CreateMaybeMessage<::coprocess::MiniRequestObject_AddParamsEntry_DoNotUse>(Arena*);
template<> ::coprocess::MiniRequestObject_ExtendedParamsEntry_DoNotUse* Arena::CreateMaybeMessage<::coprocess::MiniRequestObject_ExtendedParamsEntry_DoNotUse>(Arena*);
template<> ::coprocess::MiniRequestObject_HeadersEntry_DoNotUse* Arena::CreateMaybeMessage<::coprocess::MiniRequestObject_HeadersEntry_DoNotUse>(Arena*);
template<> ::coprocess::MiniRequestObject_ParamsEntry_DoNotUse* Arena::CreateMaybeMessage<::coprocess::MiniRequestObject_ParamsEntry_DoNotUse>(Arena*);
template<> ::coprocess::MiniRequestObject_SetHeadersEntry_DoNotUse* Arena::CreateMaybeMessage<::coprocess::MiniRequestObject_SetHeadersEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace coprocess {

// ===================================================================

class MiniRequestObject_HeadersEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<MiniRequestObject_HeadersEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<MiniRequestObject_HeadersEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  MiniRequestObject_HeadersEntry_DoNotUse();
  MiniRequestObject_HeadersEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const MiniRequestObject_HeadersEntry_DoNotUse& other);
  static const MiniRequestObject_HeadersEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MiniRequestObject_HeadersEntry_DoNotUse*>(&_MiniRequestObject_HeadersEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class MiniRequestObject_SetHeadersEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<MiniRequestObject_SetHeadersEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<MiniRequestObject_SetHeadersEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  MiniRequestObject_SetHeadersEntry_DoNotUse();
  MiniRequestObject_SetHeadersEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const MiniRequestObject_SetHeadersEntry_DoNotUse& other);
  static const MiniRequestObject_SetHeadersEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MiniRequestObject_SetHeadersEntry_DoNotUse*>(&_MiniRequestObject_SetHeadersEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class MiniRequestObject_ParamsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<MiniRequestObject_ParamsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<MiniRequestObject_ParamsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  MiniRequestObject_ParamsEntry_DoNotUse();
  MiniRequestObject_ParamsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const MiniRequestObject_ParamsEntry_DoNotUse& other);
  static const MiniRequestObject_ParamsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MiniRequestObject_ParamsEntry_DoNotUse*>(&_MiniRequestObject_ParamsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class MiniRequestObject_AddParamsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<MiniRequestObject_AddParamsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<MiniRequestObject_AddParamsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  MiniRequestObject_AddParamsEntry_DoNotUse();
  MiniRequestObject_AddParamsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const MiniRequestObject_AddParamsEntry_DoNotUse& other);
  static const MiniRequestObject_AddParamsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MiniRequestObject_AddParamsEntry_DoNotUse*>(&_MiniRequestObject_AddParamsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class MiniRequestObject_ExtendedParamsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<MiniRequestObject_ExtendedParamsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<MiniRequestObject_ExtendedParamsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  MiniRequestObject_ExtendedParamsEntry_DoNotUse();
  MiniRequestObject_ExtendedParamsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const MiniRequestObject_ExtendedParamsEntry_DoNotUse& other);
  static const MiniRequestObject_ExtendedParamsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MiniRequestObject_ExtendedParamsEntry_DoNotUse*>(&_MiniRequestObject_ExtendedParamsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class MiniRequestObject : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:coprocess.MiniRequestObject) */ {
 public:
  MiniRequestObject();
  virtual ~MiniRequestObject();

  MiniRequestObject(const MiniRequestObject& from);

  inline MiniRequestObject& operator=(const MiniRequestObject& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MiniRequestObject(MiniRequestObject&& from) noexcept
    : MiniRequestObject() {
    *this = ::std::move(from);
  }

  inline MiniRequestObject& operator=(MiniRequestObject&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MiniRequestObject& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MiniRequestObject* internal_default_instance() {
    return reinterpret_cast<const MiniRequestObject*>(
               &_MiniRequestObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(MiniRequestObject* other);
  friend void swap(MiniRequestObject& a, MiniRequestObject& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MiniRequestObject* New() const final {
    return CreateMaybeMessage<MiniRequestObject>(NULL);
  }

  MiniRequestObject* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MiniRequestObject>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MiniRequestObject& from);
  void MergeFrom(const MiniRequestObject& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MiniRequestObject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> headers = 1;
  int headers_size() const;
  void clear_headers();
  static const int kHeadersFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      headers() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_headers();

  // map<string, string> set_headers = 2;
  int set_headers_size() const;
  void clear_set_headers();
  static const int kSetHeadersFieldNumber = 2;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      set_headers() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_set_headers();

  // repeated string delete_headers = 3;
  int delete_headers_size() const;
  void clear_delete_headers();
  static const int kDeleteHeadersFieldNumber = 3;
  const ::std::string& delete_headers(int index) const;
  ::std::string* mutable_delete_headers(int index);
  void set_delete_headers(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_delete_headers(int index, ::std::string&& value);
  #endif
  void set_delete_headers(int index, const char* value);
  void set_delete_headers(int index, const char* value, size_t size);
  ::std::string* add_delete_headers();
  void add_delete_headers(const ::std::string& value);
  #if LANG_CXX11
  void add_delete_headers(::std::string&& value);
  #endif
  void add_delete_headers(const char* value);
  void add_delete_headers(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& delete_headers() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_delete_headers();

  // map<string, string> params = 6;
  int params_size() const;
  void clear_params();
  static const int kParamsFieldNumber = 6;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      params() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_params();

  // map<string, string> add_params = 7;
  int add_params_size() const;
  void clear_add_params();
  static const int kAddParamsFieldNumber = 7;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      add_params() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_add_params();

  // map<string, string> extended_params = 8;
  int extended_params_size() const;
  void clear_extended_params();
  static const int kExtendedParamsFieldNumber = 8;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      extended_params() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_extended_params();

  // repeated string delete_params = 9;
  int delete_params_size() const;
  void clear_delete_params();
  static const int kDeleteParamsFieldNumber = 9;
  const ::std::string& delete_params(int index) const;
  ::std::string* mutable_delete_params(int index);
  void set_delete_params(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_delete_params(int index, ::std::string&& value);
  #endif
  void set_delete_params(int index, const char* value);
  void set_delete_params(int index, const char* value, size_t size);
  ::std::string* add_delete_params();
  void add_delete_params(const ::std::string& value);
  #if LANG_CXX11
  void add_delete_params(::std::string&& value);
  #endif
  void add_delete_params(const char* value);
  void add_delete_params(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& delete_params() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_delete_params();

  // string body = 4;
  void clear_body();
  static const int kBodyFieldNumber = 4;
  const ::std::string& body() const;
  void set_body(const ::std::string& value);
  #if LANG_CXX11
  void set_body(::std::string&& value);
  #endif
  void set_body(const char* value);
  void set_body(const char* value, size_t size);
  ::std::string* mutable_body();
  ::std::string* release_body();
  void set_allocated_body(::std::string* body);

  // string url = 5;
  void clear_url();
  static const int kUrlFieldNumber = 5;
  const ::std::string& url() const;
  void set_url(const ::std::string& value);
  #if LANG_CXX11
  void set_url(::std::string&& value);
  #endif
  void set_url(const char* value);
  void set_url(const char* value, size_t size);
  ::std::string* mutable_url();
  ::std::string* release_url();
  void set_allocated_url(::std::string* url);

  // .coprocess.ReturnOverrides return_overrides = 10;
  bool has_return_overrides() const;
  void clear_return_overrides();
  static const int kReturnOverridesFieldNumber = 10;
  private:
  const ::coprocess::ReturnOverrides& _internal_return_overrides() const;
  public:
  const ::coprocess::ReturnOverrides& return_overrides() const;
  ::coprocess::ReturnOverrides* release_return_overrides();
  ::coprocess::ReturnOverrides* mutable_return_overrides();
  void set_allocated_return_overrides(::coprocess::ReturnOverrides* return_overrides);

  // @@protoc_insertion_point(class_scope:coprocess.MiniRequestObject)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      MiniRequestObject_HeadersEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > headers_;
  ::google::protobuf::internal::MapField<
      MiniRequestObject_SetHeadersEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > set_headers_;
  ::google::protobuf::RepeatedPtrField< ::std::string> delete_headers_;
  ::google::protobuf::internal::MapField<
      MiniRequestObject_ParamsEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > params_;
  ::google::protobuf::internal::MapField<
      MiniRequestObject_AddParamsEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > add_params_;
  ::google::protobuf::internal::MapField<
      MiniRequestObject_ExtendedParamsEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > extended_params_;
  ::google::protobuf::RepeatedPtrField< ::std::string> delete_params_;
  ::google::protobuf::internal::ArenaStringPtr body_;
  ::google::protobuf::internal::ArenaStringPtr url_;
  ::coprocess::ReturnOverrides* return_overrides_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_coprocess_5fmini_5frequest_5fobject_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MiniRequestObject

// map<string, string> headers = 1;
inline int MiniRequestObject::headers_size() const {
  return headers_.size();
}
inline void MiniRequestObject::clear_headers() {
  headers_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
MiniRequestObject::headers() const {
  // @@protoc_insertion_point(field_map:coprocess.MiniRequestObject.headers)
  return headers_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
MiniRequestObject::mutable_headers() {
  // @@protoc_insertion_point(field_mutable_map:coprocess.MiniRequestObject.headers)
  return headers_.MutableMap();
}

// map<string, string> set_headers = 2;
inline int MiniRequestObject::set_headers_size() const {
  return set_headers_.size();
}
inline void MiniRequestObject::clear_set_headers() {
  set_headers_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
MiniRequestObject::set_headers() const {
  // @@protoc_insertion_point(field_map:coprocess.MiniRequestObject.set_headers)
  return set_headers_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
MiniRequestObject::mutable_set_headers() {
  // @@protoc_insertion_point(field_mutable_map:coprocess.MiniRequestObject.set_headers)
  return set_headers_.MutableMap();
}

// repeated string delete_headers = 3;
inline int MiniRequestObject::delete_headers_size() const {
  return delete_headers_.size();
}
inline void MiniRequestObject::clear_delete_headers() {
  delete_headers_.Clear();
}
inline const ::std::string& MiniRequestObject::delete_headers(int index) const {
  // @@protoc_insertion_point(field_get:coprocess.MiniRequestObject.delete_headers)
  return delete_headers_.Get(index);
}
inline ::std::string* MiniRequestObject::mutable_delete_headers(int index) {
  // @@protoc_insertion_point(field_mutable:coprocess.MiniRequestObject.delete_headers)
  return delete_headers_.Mutable(index);
}
inline void MiniRequestObject::set_delete_headers(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:coprocess.MiniRequestObject.delete_headers)
  delete_headers_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MiniRequestObject::set_delete_headers(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:coprocess.MiniRequestObject.delete_headers)
  delete_headers_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MiniRequestObject::set_delete_headers(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  delete_headers_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:coprocess.MiniRequestObject.delete_headers)
}
inline void MiniRequestObject::set_delete_headers(int index, const char* value, size_t size) {
  delete_headers_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:coprocess.MiniRequestObject.delete_headers)
}
inline ::std::string* MiniRequestObject::add_delete_headers() {
  // @@protoc_insertion_point(field_add_mutable:coprocess.MiniRequestObject.delete_headers)
  return delete_headers_.Add();
}
inline void MiniRequestObject::add_delete_headers(const ::std::string& value) {
  delete_headers_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:coprocess.MiniRequestObject.delete_headers)
}
#if LANG_CXX11
inline void MiniRequestObject::add_delete_headers(::std::string&& value) {
  delete_headers_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:coprocess.MiniRequestObject.delete_headers)
}
#endif
inline void MiniRequestObject::add_delete_headers(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  delete_headers_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:coprocess.MiniRequestObject.delete_headers)
}
inline void MiniRequestObject::add_delete_headers(const char* value, size_t size) {
  delete_headers_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:coprocess.MiniRequestObject.delete_headers)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MiniRequestObject::delete_headers() const {
  // @@protoc_insertion_point(field_list:coprocess.MiniRequestObject.delete_headers)
  return delete_headers_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MiniRequestObject::mutable_delete_headers() {
  // @@protoc_insertion_point(field_mutable_list:coprocess.MiniRequestObject.delete_headers)
  return &delete_headers_;
}

// string body = 4;
inline void MiniRequestObject::clear_body() {
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MiniRequestObject::body() const {
  // @@protoc_insertion_point(field_get:coprocess.MiniRequestObject.body)
  return body_.GetNoArena();
}
inline void MiniRequestObject::set_body(const ::std::string& value) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:coprocess.MiniRequestObject.body)
}
#if LANG_CXX11
inline void MiniRequestObject::set_body(::std::string&& value) {
  
  body_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:coprocess.MiniRequestObject.body)
}
#endif
inline void MiniRequestObject::set_body(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:coprocess.MiniRequestObject.body)
}
inline void MiniRequestObject::set_body(const char* value, size_t size) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:coprocess.MiniRequestObject.body)
}
inline ::std::string* MiniRequestObject::mutable_body() {
  
  // @@protoc_insertion_point(field_mutable:coprocess.MiniRequestObject.body)
  return body_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MiniRequestObject::release_body() {
  // @@protoc_insertion_point(field_release:coprocess.MiniRequestObject.body)
  
  return body_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MiniRequestObject::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    
  } else {
    
  }
  body_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:coprocess.MiniRequestObject.body)
}

// string url = 5;
inline void MiniRequestObject::clear_url() {
  url_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MiniRequestObject::url() const {
  // @@protoc_insertion_point(field_get:coprocess.MiniRequestObject.url)
  return url_.GetNoArena();
}
inline void MiniRequestObject::set_url(const ::std::string& value) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:coprocess.MiniRequestObject.url)
}
#if LANG_CXX11
inline void MiniRequestObject::set_url(::std::string&& value) {
  
  url_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:coprocess.MiniRequestObject.url)
}
#endif
inline void MiniRequestObject::set_url(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:coprocess.MiniRequestObject.url)
}
inline void MiniRequestObject::set_url(const char* value, size_t size) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:coprocess.MiniRequestObject.url)
}
inline ::std::string* MiniRequestObject::mutable_url() {
  
  // @@protoc_insertion_point(field_mutable:coprocess.MiniRequestObject.url)
  return url_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MiniRequestObject::release_url() {
  // @@protoc_insertion_point(field_release:coprocess.MiniRequestObject.url)
  
  return url_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MiniRequestObject::set_allocated_url(::std::string* url) {
  if (url != NULL) {
    
  } else {
    
  }
  url_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), url);
  // @@protoc_insertion_point(field_set_allocated:coprocess.MiniRequestObject.url)
}

// map<string, string> params = 6;
inline int MiniRequestObject::params_size() const {
  return params_.size();
}
inline void MiniRequestObject::clear_params() {
  params_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
MiniRequestObject::params() const {
  // @@protoc_insertion_point(field_map:coprocess.MiniRequestObject.params)
  return params_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
MiniRequestObject::mutable_params() {
  // @@protoc_insertion_point(field_mutable_map:coprocess.MiniRequestObject.params)
  return params_.MutableMap();
}

// map<string, string> add_params = 7;
inline int MiniRequestObject::add_params_size() const {
  return add_params_.size();
}
inline void MiniRequestObject::clear_add_params() {
  add_params_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
MiniRequestObject::add_params() const {
  // @@protoc_insertion_point(field_map:coprocess.MiniRequestObject.add_params)
  return add_params_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
MiniRequestObject::mutable_add_params() {
  // @@protoc_insertion_point(field_mutable_map:coprocess.MiniRequestObject.add_params)
  return add_params_.MutableMap();
}

// map<string, string> extended_params = 8;
inline int MiniRequestObject::extended_params_size() const {
  return extended_params_.size();
}
inline void MiniRequestObject::clear_extended_params() {
  extended_params_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
MiniRequestObject::extended_params() const {
  // @@protoc_insertion_point(field_map:coprocess.MiniRequestObject.extended_params)
  return extended_params_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
MiniRequestObject::mutable_extended_params() {
  // @@protoc_insertion_point(field_mutable_map:coprocess.MiniRequestObject.extended_params)
  return extended_params_.MutableMap();
}

// repeated string delete_params = 9;
inline int MiniRequestObject::delete_params_size() const {
  return delete_params_.size();
}
inline void MiniRequestObject::clear_delete_params() {
  delete_params_.Clear();
}
inline const ::std::string& MiniRequestObject::delete_params(int index) const {
  // @@protoc_insertion_point(field_get:coprocess.MiniRequestObject.delete_params)
  return delete_params_.Get(index);
}
inline ::std::string* MiniRequestObject::mutable_delete_params(int index) {
  // @@protoc_insertion_point(field_mutable:coprocess.MiniRequestObject.delete_params)
  return delete_params_.Mutable(index);
}
inline void MiniRequestObject::set_delete_params(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:coprocess.MiniRequestObject.delete_params)
  delete_params_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MiniRequestObject::set_delete_params(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:coprocess.MiniRequestObject.delete_params)
  delete_params_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MiniRequestObject::set_delete_params(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  delete_params_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:coprocess.MiniRequestObject.delete_params)
}
inline void MiniRequestObject::set_delete_params(int index, const char* value, size_t size) {
  delete_params_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:coprocess.MiniRequestObject.delete_params)
}
inline ::std::string* MiniRequestObject::add_delete_params() {
  // @@protoc_insertion_point(field_add_mutable:coprocess.MiniRequestObject.delete_params)
  return delete_params_.Add();
}
inline void MiniRequestObject::add_delete_params(const ::std::string& value) {
  delete_params_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:coprocess.MiniRequestObject.delete_params)
}
#if LANG_CXX11
inline void MiniRequestObject::add_delete_params(::std::string&& value) {
  delete_params_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:coprocess.MiniRequestObject.delete_params)
}
#endif
inline void MiniRequestObject::add_delete_params(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  delete_params_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:coprocess.MiniRequestObject.delete_params)
}
inline void MiniRequestObject::add_delete_params(const char* value, size_t size) {
  delete_params_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:coprocess.MiniRequestObject.delete_params)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MiniRequestObject::delete_params() const {
  // @@protoc_insertion_point(field_list:coprocess.MiniRequestObject.delete_params)
  return delete_params_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MiniRequestObject::mutable_delete_params() {
  // @@protoc_insertion_point(field_mutable_list:coprocess.MiniRequestObject.delete_params)
  return &delete_params_;
}

// .coprocess.ReturnOverrides return_overrides = 10;
inline bool MiniRequestObject::has_return_overrides() const {
  return this != internal_default_instance() && return_overrides_ != NULL;
}
inline const ::coprocess::ReturnOverrides& MiniRequestObject::_internal_return_overrides() const {
  return *return_overrides_;
}
inline const ::coprocess::ReturnOverrides& MiniRequestObject::return_overrides() const {
  const ::coprocess::ReturnOverrides* p = return_overrides_;
  // @@protoc_insertion_point(field_get:coprocess.MiniRequestObject.return_overrides)
  return p != NULL ? *p : *reinterpret_cast<const ::coprocess::ReturnOverrides*>(
      &::coprocess::_ReturnOverrides_default_instance_);
}
inline ::coprocess::ReturnOverrides* MiniRequestObject::release_return_overrides() {
  // @@protoc_insertion_point(field_release:coprocess.MiniRequestObject.return_overrides)
  
  ::coprocess::ReturnOverrides* temp = return_overrides_;
  return_overrides_ = NULL;
  return temp;
}
inline ::coprocess::ReturnOverrides* MiniRequestObject::mutable_return_overrides() {
  
  if (return_overrides_ == NULL) {
    auto* p = CreateMaybeMessage<::coprocess::ReturnOverrides>(GetArenaNoVirtual());
    return_overrides_ = p;
  }
  // @@protoc_insertion_point(field_mutable:coprocess.MiniRequestObject.return_overrides)
  return return_overrides_;
}
inline void MiniRequestObject::set_allocated_return_overrides(::coprocess::ReturnOverrides* return_overrides) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(return_overrides_);
  }
  if (return_overrides) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      return_overrides = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, return_overrides, submessage_arena);
    }
    
  } else {
    
  }
  return_overrides_ = return_overrides;
  // @@protoc_insertion_point(field_set_allocated:coprocess.MiniRequestObject.return_overrides)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace coprocess

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_coprocess_5fmini_5frequest_5fobject_2eproto
